---
title: "The Premier League's Most Overpaid Players"
author: "Micah Williams"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(tidyverse)
library(dplyr)
library(gt)
```

```{r import, message = F}

# name cleaning process:
  # filter out single-named players (ex. Willian or Rodri)
  # separate first name from last name
  # switch name order ('Firstname' 'Lastname' instead of 'Lastname' 'Firstname')
  # recombine in new column, drop original name columns

# import contract data - 1.29 = current pound-to-dollar exchange rate
pay_2020 <- read_csv('data/pay_complete.csv', na = c(NA, '', '-')) %>%
  mutate(contract_length = parse_number(contract_length),
         transfer_fee = 1.29*transfer_fee,
         contract_value = 1.29*contract_value)

# import player statistics from '18-'19 season
stats_2019 <- read_csv('data/stats_complete_2018.csv') %>% mutate('season' = 2019)

# import player statistics from '19-'20 season
stats_2020 <- read_csv('data/stats_complete.csv') %>% mutate('season' = 2020) 

# combine '19-'20 data with '18-'19 data
combined <- stats_2020 %>% bind_rows(stats_2019)

# save rows with single-name players
single_names <- combined %>% filter(!str_detect(player, ','))

# clean player names
combined <- combined %>%
  filter(str_detect(player, ',')) %>%
  separate(player, c('lastname','firstname'), ', ') %>%
  mutate(player = paste(firstname, lastname, sep = ' ')) %>%
  select(player, everything()) %>%
  select(-c(firstname, lastname)) %>%
  bind_rows(single_names)

prem <- pay_2020 %>%
  inner_join(combined, by = 'player') %>%
  mutate('total_price' = contract_value + transfer_fee)

rm(single_names, stats_2020, stats_2019)
```


```{r}
prem %>% 
  group_by(team) %>% 
  arrange(desc(contract_value)) %>%
  select(team, player, position, age, contract_value) %>%
  slice(1) %>%
  ungroup() %>%
  arrange(desc(contract_value)) %>%
  gt() %>%
  cols_align('auto') %>%
  fmt_currency(columns = vars(contract_value),
               currency = 'USD') %>%
  cols_label(team = 'Team',
             player = 'Player',
             position = 'Position',
             age = 'Age',
             contract_value = 'Contract')

prem %>% 
  summarize(mean_age = round(mean(age, na.rm = TRUE),2),
            avg_games = round(mean(games),2),
            avg_contract = mean(contract_value)/1000000,
            avg_price = mean(total_price, na.rm = TRUE)/1000000) %>%
  gt() %>%
  cols_align('center') %>%
  tab_header(title = 'Averages') %>%
  fmt_currency(columns = vars(avg_contract, avg_price),
               currency = 'USD') %>%
  cols_label(mean_age = 'Age (years)',
             avg_games = 'Games Played',
             avg_contract = 'Contract (Million $)',
             avg_price = 'Contract + Transfer Fee (Million $)')
```

